### PR TITLE
live scale test

### PR DESCRIPTION
**Pull request by konstan**
The live test is in `clj/test/live/scalable-run.clj`.
Tested again after the migration from `lein` to `boot` (126dd8a).
Master with `boot` was already merged in.

Connected to #3

### CODE REVIEW

**Comment by konstan** [comment]
The problem with inability to change component name and new VM size when executing  

```
12:14 $ ./test/live/scalable-run.clj blah 123
Checking out default-deps-3.1-SNAPSHOT.jar...
*command-line-args* = nil
comp-name = testvm
test-instance-type = Tiny
12:15 $
```

is due to migration from lein to boot.  lein-exec plugin was defining `*command-line-args*` which I was using to parse CLI params, but it doesn't exist with `boot`.  I'll check if anything similar for providing CLI params to the script is available in `boot`.

**Comment by konstan** [comment]
I found a way to make it work with `boot`.  Implemented.  Now testing on a real deployment.  Will be pushing the change shortly.

**Comment by loomis** [comment]
Ok, cool.  Let me know when to test again.

**Comment by konstan** [comment]
Result of the test.

```
14:09 $ ./test/live/scalable-run.clj testvmABC Medium
Checking out default-deps-3.1-SNAPSHOT.jar...
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
   - Live test of the SlipStream clojure API library via scaling SlipStream run.
   - Component to scale: 'testvmABC'
   - VM instance type for diagonal scaling: 'Medium'
:::
::: Run:
{:url "https://nuv.la/run/911eba8b-d950-46e4-931f-154c35722445",
 :state "Ready",
 :scalable true,
 :can-scale true,
 :aborted false,
 :abort-msg ""}
:::
::: Starting tests.
   - Waiting for Ready state.
   - Check if run is scalable.
((testvmABC.1 operational))
:::
::: Artificially abort the run and then recover from the abort.
:::
::: Scale up. Manual wait.
   - Waiting for Ready state.
:::
::: Scale down by IDs. Manual wait.
   - Waiting for Ready state.
:::
::: Diagonal scale up action (with internal wait). Providing VM size RTPs.
   - 'component id' => 'instance size'
   - 2 => Small
   - 4 => Medium
   - 5 => Medium
:::
::: Scale down action (with internal wait). Remove instances by ids: (2 4)
:::
::: Scale down action (with internal wait). Remove a number of instances.
:::
::: Termintating run.
:::
::: Validation.
:::
::: Test finished successfully.
✔ ~/code/SlipStreamClientAPI/clj [issue_#3-live-test-scale|✚ 2⚑ 1]
14:17 $
```

**Comment by konstan** [comment]
The change is pushed.  Please test.

**Comment by loomis** [comment]
Works for me.  Merging...

**Pull request merged**
