### PR TITLE
update to run demo and live test

### PR DESCRIPTION
**Pull request by konstan**
Because the introduction of the `authn` and `app` namespaces opened the possibility to run the tests in a self-contained manner (request endpoint/credentials/application uri from the user, authenticate to the service and start the application deployment) the following changes were made to demo of the `run` namespace and the live scalable run test
- run demo:
  - extended to demo how to authenticate to SS service and deploy an application by using two extra namespaces: `authn` and `app`
  - Validation: follow documentation in `jar/doc/demo-run-scale.clj`
- live scalable run test:
  - updated the set of CLI parameters of `scalable-run.clj` script to accept user/pass/app-uri/etc.
  - authenticate and start the app deployment.
  - Validation: follow documentation in `jar/test/live/scalable-run.clj`

### CODE REVIEW

**Comment by loomis** [comment]
Can you add to the documentation how to control the logging from kvlt?  The output is distracting and makes it difficult to see what the actual results are. 

For me, the test through the REPL worked fine.  The automated test didn't finish correctly, but it was difficult to understand what went wrong because of the kvlt logging.  I'll try again when I can turn it off.

**Comment by konstan** [comment]
I'll check now how to switch it off.  
The easiest is to change version number of kvlt from 0.1.1 to `[io.nervous/kvlt "0.1.0"]`.

**Comment by konstan** [comment]
Confirmed: changing to `[io.nervous/kvlt "0.1.0"]` turns the logging off w/o any changes in our logging properties files that are visible on the classpath.

I'll check with kvlt developer why this is the case in 0.1.1.

**Comment by loomis** [comment]
An issue has been opened to add the logging configuration for kvlt; see #27.

**Pull request merged**
