### PR TITLE
Feature/using cljs

### PR DESCRIPTION
**Pull request by loomis**
Connected to SixSq/tasklist#732.

### CODE REVIEW

**Comment by loomis** [comment]
@konstan: This probably isn't ready quite yet to be merged.  But I'd appreciate feedback on:
- The organization of the namespaces, particularly the separation between the synchronous and asynchronous versions of functions.
- The possibility of moving the lifecycle tests to the functional tests repository.
- Any impact on the existing functional tests.

**Comment by konstan** [comment]
@loomis 

> - The organization of the namespaces, particularly the separation between the synchronous and asynchronous versions of functions.

Looks good to me.

> - The possibility of moving the lifecycle tests to the functional tests repository.

+1 and also need to move `live/scalable-run.clj` there as well. 
There is this demo script `doc/demo-run-scale.clj`, which is a sequence of repl commands (no assertions).  The problem is that it doesn't get regularly tested.  We can create a `boot` script out of it and run it as a functional test as well.  And if it breaks in functional tests repo -- we fix it and update here as well.  (Keeping demos up-to-date and working is always good). 

> - Any impact on the existing functional tests.

I'll compile the client API jar from the branch and test with it to see if there is any impact.

**Comment by loomis** [comment]
Thanks for the feedback.  Another (longer-term) option on the second point would be to create a SS server that can be started as part of the tests.  In principle, there is nothing limiting this as the main server and database could both be started from unit tests.  That would certainly take some investment of time, however.

**Comment by konstan** [comment]
For the record.  Up to now, there is no regression in the functional tests.

**Comment by konstan** [comment]
Added an issue to move lifecycle tests to the functional tests repo https://github.com/slipstream/SlipStreamClientAPI/issues/36

**Comment by konstan** [comment]
Ready to be merged on my side.  Please let me know if there are any changes you want to push.

**Comment by loomis** [comment]
Go.

**Pull request merged**
