### PR TITLE
switch to using boot for build

### PR DESCRIPTION
**Pull request by loomis**
Connected to slipstream/SlipStreamServer#616.

### CODE REVIEW

**Comment by konstan** [comment]
Building of RPM fails with not being able to find `jar-with-dependencies` artefact.  I see that building JAR doesn’t produce it.  Did you remove it on purpose?

**Comment by konstan** [comment]
I've updated dependencies in `clj/resources/deps.edn`.

**Comment by loomis** [comment]
The main jar file is already an uberjar.  I've adjusted the classifier to pull the main jar file.

**Comment by konstan** [comment]
I see two jar artefacts are being produced.

```
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ SlipStreamClientAPI-jar ---
[INFO] Building jar: /Users/konstan/SixSq/code/SlipStreamClientAPI-boot/clj/target/SlipStreamClientAPI-jar-3.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ SlipStreamClientAPI-jar ---
[INFO] Installing /Users/konstan/SixSq/code/SlipStreamClientAPI-boot/clj/target/SlipStreamClientAPI-jar-3.1-SNAPSHOT.jar to /Users/konstan/.m2/repository/com/sixsq/slipstream/SlipStreamClientAPI-jar/3.1-S
NAPSHOT/SlipStreamClientAPI-jar-3.1-SNAPSHOT.jar
[INFO] Installing /Users/konstan/SixSq/code/SlipStreamClientAPI-boot/clj/pom.xml to /Users/konstan/.m2/repository/com/sixsq/slipstream/SlipStreamClientAPI-jar/3.1-SNAPSHOT/SlipStreamClientAPI-jar-3.1-SNAP
SHOT.pom
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:exec (boot-build) @ SlipStreamClientAPI-jar ---
Checking out default-deps-3.1-SNAPSHOT.jar...
Writing pom.xml and pom.properties...
Adding uberjar entries...
Writing SlipStreamClientAPI-3.1-SNAPSHOT.jar...
Installing SlipStreamClientAPI-3.1-SNAPSHOT.jar...
Writing target dir(s)...
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:attach-artifact (add-jar) @ SlipStreamClientAPI-jar ---
```

NB! when calling `--- exec-maven-plugin:1.4.0:exec (boot-build) @ SlipStreamClientAPI-jar ---`, `target/`directory gets cleaned up, making /Users/konstan/SixSq/code/SlipStreamClientAPI-boot/clj/target/SlipStreamClientAPI-jar-3.1-SNAPSHOT.jar disappear. Not a big problem, though -- just confusing.

```
✔ ~/code/SlipStreamClientAPI-boot [feature/boot-build|✚ 1]
11:35 $ ll /Users/konstan/.m2/repository/com/sixsq/slipstream/SlipStreamClientAPI-jar/3.1-SNAPSHOT/
total 56
-rw-r--r--  1 konstan  staff   997 Mar 18 11:03 SlipStreamClientAPI-jar-3.1-SNAPSHOT-jar-with-dependencies.jar.lastUpdated
-rw-r--r--  1 konstan  staff   997 Mar 18 11:31 SlipStreamClientAPI-jar-3.1-SNAPSHOT-jar.jar.lastUpdated
-rw-r--r--  1 konstan  staff  2980 Mar 18 11:30 SlipStreamClientAPI-jar-3.1-SNAPSHOT.jar
-rw-r--r--  1 konstan  staff  5296 Mar 18 11:30 SlipStreamClientAPI-jar-3.1-SNAPSHOT.pom
-rw-r--r--  1 konstan  staff   219 Mar 18 11:30 _remote.repositories
-rw-r--r--  1 konstan  staff   723 Mar 18 11:30 maven-metadata-local.xml
✔ ~/code/SlipStreamClientAPI-boot [feature/boot-build|✚ 1]
11:35 $ ll /Users/konstan/.m2/repository/com/sixsq/slipstream/SlipStreamClientAPI/3.1-SNAPSHOT/
total 44536
-rw-r--r--  1 konstan  staff  22785725 Mar 18 11:31 SlipStreamClientAPI-3.1-SNAPSHOT.jar
-rw-r--r--  1 konstan  staff      3895 Mar 18 11:31 SlipStreamClientAPI-3.1-SNAPSHOT.pom
-rw-r--r--  1 konstan  staff       204 Mar 18 11:31 _maven.repositories
-rw-r--r--  1 konstan  staff       172 Mar 18 11:30 _remote.repositories
-rw-r--r--  1 konstan  staff       719 Mar 18 11:31 maven-metadata-local.xml
✔ ~/code/SlipStreamClientAPI-boot [feature/boot-build|✚ 1]
11:35 $
```

RPM generation in `rpm/pom.xml` still depends on `jar-with-dependencies` classified one, which is no longer being build.

I'll remove `--- maven-jar-plugin:2.6:jar (default-jar) @ SlipStreamClientAPI-jar ---` and will depend on `SlipStreamClientAPI` in RPM pom.

The size of the generated uberjar is 22M -- CRAZY!

```
11:50 $ ll -h /Users/konstan/.m2/repository/com/sixsq/slipstream/SlipStreamClientAPI/3.1-SNAPSHOT/SlipStreamClientAPI-3.1-SNAPSHOT.jar
-rw-r--r--  1 konstan  staff    22M Mar 18 11:31 /Users/konstan/.m2/repository/com/sixsq/slipstream/SlipStreamClientAPI/3.1-SNAPSHOT/SlipStreamClientAPI-3.1-SNAPSHOT.jar
```

**Comment by konstan** [comment]
Running tests produces the output below.  `Ran 0 tests containing 0 assertions in 0 msecs`
Is it actually running any tests?

```
[INFO] --- exec-maven-plugin:1.4.0:exec (boot-test) @ SlipStreamClientAPI-jar ---
Checking out default-deps-3.1-SNAPSHOT.jar...
Writing pom.xml and pom.properties...
Compiling 1/6 com.sixsq.slipstream.clj-client.lib.context...
Compiling 2/6 com.sixsq.slipstream.clj-client.lib.http-impl...
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Compiling 3/6 com.sixsq.slipstream.clj-client.lib.run...
Compiling 4/6 com.sixsq.slipstream.clj-client.lib.run-impl...
Compiling 5/6 com.sixsq.slipstream.clj-client.lib.utils...
Compiling 6/6 com.sixsq.slipstream.clj-client.run...
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Testing com.sixsq.slipstream.clj-client.lib.context

Testing com.sixsq.slipstream.clj-client.lib.http-impl

Testing com.sixsq.slipstream.clj-client.lib.run

Testing com.sixsq.slipstream.clj-client.lib.run-impl

Testing com.sixsq.slipstream.clj-client.lib.utils

Testing com.sixsq.slipstream.clj-client.run

Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Ran 0 tests containing 0 assertions in 0 msecs
0 failures, 0 errors.
[INFO]
```

**Comment by loomis** [comment]
The tests were not included in the sources/resource so were not run.  They were added with the last commit.

**Comment by konstan** [comment]
I wasn't able to remove building of `(default-jar)`.  
The RPM generation related changes are in 0be269a

**Comment by loomis** [comment]
How are you building the module?  I only see 1 jar file being created via the maven build.

**Comment by konstan** [comment]
Extra cleanup of `clj/pom.xml` 2ce70d9  Please check.

After all the changes I can now build RPM with the uberjar.

**Pull request merged**
