### PR TITLE
update test-cljs tasks, remove workarounds for tests

### PR DESCRIPTION
**Pull request by loomis**
Connected to #53.

### CODE REVIEW

**Comment by konstan** [comment]
@loomis ClojureScript tests fail for me on the branch
```
$ boot test-cljs
Adding: ([doo "0.1.7"]) to :dependencies
Compiling ClojureScript...
• cljs_test/generated_test_suite.js
Dec 19, 2016 11:52:36 AM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/konstan/.boot/cache/tmp/Users/konstan/SixSq/code/community/SlipStreamClojureAPI/jar/pgg/-dfi377/cljs_test/generated_test_suite.out/promesa/core.js:478: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return it__$1.catch(((function (it__$1){
              ^

Dec 19, 2016 11:52:36 AM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/konstan/.boot/cache/tmp/Users/konstan/SixSq/code/community/SlipStreamClojureAPI/jar/pgg/-dfi377/cljs_test/generated_test_suite.out/promesa/core.js:792: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return p.finally(callback);
         ^

Dec 19, 2016 11:52:36 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 2 warning(s)

;; ======================================================================
;; Testing with Phantom:

TypeError: expecting a function but got [object Null]

  phantomjs://code/phantom6008002702845457215.js:81 in onError
clojure.lang.ExceptionInfo: TypeError: expecting a function but got [object Null]  phantomjs://code/phantom6008002702845457215.js:81 in onError
    data: {:file
           "/var/folders/8s/ct1psdgd7618_5_n_8clwdhm0000gn/T/boot.user6113774567742044197.clj",
           :line 53}
java.lang.RuntimeException: TypeError: expecting a function but got [object Null]  phantomjs://code/phantom6008002702845457215.js:81 in onError
          crisptrutski.boot-cljs-test/run-tests!/fn  boot_cljs_test.clj:  122
crisptrutski.boot-cljs-test/run-tests!/invokeStatic  boot_cljs_test.clj:  147
             crisptrutski.boot-cljs-test/run-tests!  boot_cljs_test.clj:  110
      crisptrutski.boot-cljs-test/eval1295/fn/fn/fn  boot_cljs_test.clj:  166
                  adzerk.boot-cljs/eval556/fn/fn/fn       boot_cljs.clj:  208
                  adzerk.boot-cljs/eval504/fn/fn/fn       boot_cljs.clj:  135
      crisptrutski.boot-cljs-test/eval1225/fn/fn/fn  boot_cljs_test.clj:   96
                                boot.core/run-tasks            core.clj:  938
                                  boot.core/boot/fn            core.clj:  948
                clojure.core/binding-conveyor-fn/fn            core.clj: 1938
                                                ...
$ echo $?
1
$
```

On master the tests pass

```
$ boot test-cljs
Writing output.cljs.edn...
Writing cljs_test/suite.cljs...
Compiling ClojureScript...
WARNING: Replacing ClojureScript compiler option :main with automatically set value.
• output.js
Dec 19, 2016 11:54:09 AM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/konstan/.boot/cache/tmp/Users/konstan/SixSq/code/community/SlipStreamClojureAPI/jar/pj4/-vfw9cv/output.out/promesa/core.js:478: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return it__$1.catch(((function (it__$1){
              ^

Dec 19, 2016 11:54:09 AM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/konstan/.boot/cache/tmp/Users/konstan/SixSq/code/community/SlipStreamClojureAPI/jar/pj4/-vfw9cv/output.out/promesa/core.js:792: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
return p.finally(callback);
         ^

Dec 19, 2016 11:54:09 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 2 warning(s)
Running cljs tests...
TypeError: expecting a function but got [object Null]

  phantomjs://code/phantom8112587331651435773.js:81 in onError
$ echo $?
0
$
```

**Comment by loomis** [comment]
Did you test with the PR on the SlipStream repository applied?  The dependency updates need to be applied at the same time.

**Comment by konstan** [comment]
Yes, tested after applying https://github.com/slipstream/SlipStream/pull/188 locally.

**Comment by konstan** [comment]
@loomis I just tried again and worked :( Here is my history from the window of SlipStream project (`mcism` is my alias for `mvn clean install -DskipModules`)
```
  570  git co feature/update-test-cljs
  571  git pull
  572  git pull
  573  mcism
  574  ll
  575  git co feature/update-test-cljs
  576  mcism
  577  git pull
  578  history
```
After I ran git co on line 575 ... the tests pass.  I don't know why 570..573 didn't have any effect... Strange.

**Comment by konstan** [comment]
Validated again.  Tests pass.  Merging.  Sorry for the hiccup. :-/

**Pull request merged**
